# Generated by Django 4.0 on 2022-05-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppVPIMs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('anio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono_contacto', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='amplificador',
            old_name='marca',
            new_name='modelo_ampli',
        ),
        migrations.RenameField(
            model_name='bajo',
            old_name='anio',
            new_name='cuerdas_bajo',
        ),
        migrations.RenameField(
            model_name='bajo',
            old_name='marca',
            new_name='modelo_bajo',
        ),
        migrations.RenameField(
            model_name='guitarra',
            old_name='anio',
            new_name='cuerdas_guitarra',
        ),
        migrations.RenameField(
            model_name='guitarra',
            old_name='marca',
            new_name='modelo_guitarra',
        ),
        migrations.RemoveField(
            model_name='amplificador',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='amplificador',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='amplificador',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='bajo',
            name='cuerdas',
        ),
        migrations.RemoveField(
            model_name='bajo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='bajo',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='bajo',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='guitarra',
            name='cuerdas',
        ),
        migrations.RemoveField(
            model_name='guitarra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='guitarra',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='guitarra',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='pedal',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='pedal',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pedal',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='pedal',
            name='precio',
        ),
        migrations.AddField(
            model_name='amplificador',
            name='instrumento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppVPIMs.instrumento'),
        ),
        migrations.AddField(
            model_name='bajo',
            name='instrumento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppVPIMs.instrumento'),
        ),
        migrations.AddField(
            model_name='guitarra',
            name='instrumento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppVPIMs.instrumento'),
        ),
        migrations.AddField(
            model_name='pedal',
            name='instrumento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppVPIMs.instrumento'),
        ),
    ]
