# Generated by Django 4.0 on 2022-05-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVPIMs', '0002_instrumento_rename_marca_amplificador_modelo_ampli_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amplificador',
            old_name='modelo_ampli',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='bajo',
            old_name='cuerdas_bajo',
            new_name='cuerdas',
        ),
        migrations.RenameField(
            model_name='bajo',
            old_name='modelo_bajo',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='guitarra',
            old_name='cuerdas_guitarra',
            new_name='cuerdas',
        ),
        migrations.RenameField(
            model_name='guitarra',
            old_name='modelo_guitarra',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='amplificador',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='bajo',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='guitarra',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='pedal',
            name='instrumento',
        ),
        migrations.AddField(
            model_name='amplificador',
            name='anio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amplificador',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='amplificador',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amplificador',
            name='telefono_contacto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bajo',
            name='anio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bajo',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bajo',
            name='modelo',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bajo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bajo',
            name='telefono_contacto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitarra',
            name='anio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guitarra',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitarra',
            name='modelo',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitarra',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitarra',
            name='telefono_contacto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedal',
            name='anio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedal',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedal',
            name='marca',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedal',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedal',
            name='telefono_contacto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Instrumento',
        ),
    ]
